### ISSUE TITLE
Write protoc script that uses docker

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-plugin-go#51]
Potentially namely/protoc

This will simplify the ability for people to generate the code or for us to do comparisons in CI without having to install all the tooling manually.

**Comment by bflad** [comment]
Over time this has not been an issue since there are few folks who ever touch the Protocol Buffers definitions and installation of `protoc` is relatively straightforward via Homebrew, GitHub Actions, etc. 👍
