### ISSUE TITLE
Add Walk and Transform to tftypes

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-plugin-go#53]
### Use cases

Walk:

* `IsFullyKnown` is a special case of `Walk` as an example
* Validation

Transform:

* Dynamic returns things that may possibly be lists as tuples, especially if there is a field mismatch due to limited info in the dynamic, and in some providers they need to be simplified to lists (kubernetes-alpha for example)
* Applying defaults to an object from schema

### Proposal

(similar to cty)

Since these implementations are not opinionated and leverage existing type/path info in the tftypes package, hopefully something that makes more sense in this repo as opposed to an outside one.

**Comment by paddycarver** [comment]
For reference, I believe this is referring to [Walk](https://pkg.go.dev/github.com/zclconf/go-cty/cty/#Walk) and [Transform](https://pkg.go.dev/github.com/zclconf/go-cty/cty/#Transform)

**Comment by paddycarver** [comment]
I can see an argument for including them in `tftypes`, I think more than anything I'd just want to think about stability. How likely are we to get the implementation right before v1? How likely is that implementation to change in the future?

I don't know the answer to those offhand, and they deserve some thought, but I'm not knee-jerk opposed to it.

**Comment by paultyng** [comment]
Yeah no rush on these I think. Worth checking how much they changed in cty as well but the signatures look pretty straightforward.

**Comment by paddycarver** [comment]
I think my concern is just that we'll want something that makes sense in the context of the SDK but not in the context of cty. For example, if we end up doing telemetry/logging/whatever, the function signature as it exists makes it awkward to inject those into the function being called, meaning its operations and decisions won't be observable. Which may not be the end of the world, but I think we should just think a bit about that kind of difference and whether there's anything else like that that may crop up.

**Comment by paultyng** [comment]
In most scenarios I've used walk-like funcs (ie filepath, etc.) or things with callbacks you inject that stuff via closure, so it wouldn't be part of the signature, but happy to let this happen organically somewhat. We can see what @alexsomesan comes up with as well.

**Comment by paddycarver** [comment]
Yeah, I think that's a really good call, and we could always have a helper to inject stuff into them, I suppose. Mostly just want to think through some of the future design directions a bit and see if the signatures and design all hold up.
