### ISSUE TITLE
QoL:  Make argument to AttributePath.WithElementKeyInt an int (not int64)

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform-plugin-go#59]
### terraform-plugin-go

```
0.2.1
```

### Use cases
When iterating over slices in Go with:
```
for i, v := range mySlice { ... }
```
The type of `i` tends to be `int`. 
Since this seems likely to be the most common source for the value passed into `WithElementKeyInt()` it'd be nice to not have to always cast it into `int64` to make the compiler happy.

Purely from a developer quality of life perspective, I would suggest to make the argument an int.
That is:
```
func (a *AttributePath) WithElementKeyInt(key int) { ... }
```

**Comment by bflad** [comment]
Having been slightly annoyed by this myself, I think it would be nice to at least provide the easier option here given the expected usage. I wonder if for protocol compatibility we should introduce a separate `WithElementKeyInt64(key int64)` in addition to updating `WithElementKeyInt()` although having `2147483647` elements would likely have other issues. 😄
