### ISSUE TITLE
QoL: Make tfprotov5.Diagnostic.Attribute a value instead of a pointer

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform-plugin-go#61]
### terraform-plugin-go version

```
v0.2.1
```

### Use cases

Now that AttributePath.With* methods return values and can be chained, it's become a bit awkward to construct 
`tfprotov4.Diagnostic` with it because the `Attibute` in `Diagnostic` is a pointer. This requires a additional intermediate variable off of which to collect the pointer.
Here's a real-life example (Kubernetes alpha provider):
```go
for key, present := range validKeys {
    if !present {
        kp := att.WithAttributeName(key)
        resp.Diagnostics = append(resp.Diagnostics, &tfprotov5.Diagnostic{
            Severity:  tfprotov5.DiagnosticSeverityError,
            Summary:   `Required attribute key missing from "manifest" value`,
            Detail:    fmt.Sprintf("'%s' attribute key is missing from manifest configuration", key),
            Attribute: &kp,
        })
    }
}
```

### Proposal

Making `tfprotov5.Diagnostic.Attribute` be of type `tftypes.AttributePath` would allow an expression like `att.WithAttributeName(key)` to be passed directly in the Diagnostic literal, like this:
```go
tfprotov5.Diagnostic{
            Severity:  tfprotov5.DiagnosticSeverityError,
            Summary:   `Required attribute key missing from "manifest" value`,
            Detail:    fmt.Sprintf("'%s' attribute key is missing from manifest configuration", key),
            Attribute: att.WithAttributeName(key),
        }
```

**Comment by paddycarver** [comment]
I think I'd rather make the With* methods return a pointer. A nil AttributePath has meaning, I think, and so we'd want to preserve that. I think if we continue having the steps defensively copied but return pointers, that would make the use case here work. Right?

**Comment by alexsomesan** [comment]
I think that would be just as nice. From the UX point of view, the end goal is that we don't have to thread the AttributePaths through an intermediate variable.
