### ISSUE TITLE
Implement Terraform plugin client

### ISSUE THREAD

**Issue by pazderak** [hashicorp/terraform-plugin-go#64]
### terraform-plugin-go version

```
{
	"Path": "github.com/hashicorp/terraform-plugin-go",
	"Version": "v0.2.1",
	"Replace": {
		"Path": "github.com/pazderak/terraform-plugin-go",
		"Version": "v0.2.1",
		"Time": "2021-01-07T17:53:07Z",
		"Dir": "/home/kpazdera/go/pkg/mod/github.com/pazderak/terraform-plugin-go@v0.2.1",
		"GoMod": "/home/kpazdera/go/pkg/mod/cache/download/github.com/pazderak/terraform-plugin-go/@v/v0.2.1.mod"
	},
	"Dir": "/home/kpazdera/go/pkg/mod/github.com/pazderak/terraform-plugin-go@v0.2.1",
	"GoMod": "/home/kpazdera/go/pkg/mod/cache/download/github.com/pazderak/terraform-plugin-go/@v/v0.2.1.mod"
}
```

### Use cases

I want to create a separate binary which will be able to use Terraform plugins. This binary will do the import of the existing resource to Terraform state. Finding of resources using Terraform plugin system will provide an unified way how to check a resource existence.

### Proposal

Implementing a client counterpart to the existing GRPC server will allow to re-use the existing code. Client itself can be used in the main terraform binary instead of existing GRPC client or in any third-party binary.

**Comment by paddycarver** [comment]
I think this is out of scope for this project, and is probably better suited to an issue on the hashicorp/terraform repo. Going to close this out as wontfix.
