### ISSUE TITLE
Panic when transforming an empty tftypes.Value

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-go#92]
### terraform-plugin-go version

```
v0.3.1
```

### Relevant provider source code

Confidential and under NDA, unfortunately.

### Terraform Configuration Files

Confidential and under NDA, unfortunately.

### Expected Behavior

An error should be returned, or the tftypes.Value should be built out to have just the transformed data in it.

### Actual Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x119e65e]
goroutine 25 [running]:
github.com/hashicorp/terraform-plugin-go/tftypes.transform(0xc000341848, 0x0, 0x0, 0x0, 0x0, 0xc0005bec98, 0x0, 0x1d91a28, 0xc000341830, 0x0, ...)
	/[snip]/github.com/hashicorp/terraform-plugin-go@v0.3.1/tftypes/walk.go:179 +0x37e
github.com/hashicorp/terraform-plugin-go/tftypes.Transform(...)
	/[snip]/github.com/hashicorp/terraform-plugin-go@v0.3.1/tftypes/walk.go:112
```

**Comment by bflad** [comment]
I suspect that this is occurring due to being passed a `nil` or `Value{}` directly, which would panic both with the old (`Is()`) and new (`UsableAs()`) logic:

```go
newVal.Type().UsableAs(ty)
```

Should the `transform()` function return early or return an error at the beginning when encountering this situation?
